Packets <- {
	"REGISTER": 59,
	"SHOW_REGISTER": 60,
	"HIDE_REGISTER": 61,
	"REQUEST_REGISTER_UI": 94,
	"HYDRA_CAM": 95,
	"HYDRA_CAM_HELLO": 96,
	"SCOREBOARD": 97,
	"HYDRA_CAM_CYCLE": 98,
	"SELECT_PACK": 99,
	"SHOW_PACKS": 100,
	"HIDE_PACKS": 101,
	"ROUND_END_STATS": 102,
	"REQUEST_SHOW_PACKS": 103,
	"LOBBY_LEADERBOARD": 104,
	"PACK_FEEDBACK": 105,
	"REQUEST_HIDE_LEADERBOARD": 106,
};

HydraCam <- {
	"OFF": -1,
	"DEFAULT": 0,
	"CHASE": 1,
	"SIDE": 2,
	"TACTICAL": 3,
};

Teams <- {
	"ESCORT": 1,
	"DEFEND": 2,
};
